// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/spectrum.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSpectrumInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 495632105;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_manny_ui',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AudioBuffer> crateApiSpectrumAudioBufferDecode({
    required List<int> fileBytes,
    required String fileExtension,
  });

  double crateApiSpectrumAudioBufferDurationMs({required AudioBuffer that});

  bool crateApiSpectrumAudioBufferHasData({required AudioBuffer that});

  int crateApiSpectrumAudioBufferSampleRate({required AudioBuffer that});

  Float32List crateApiSpectrumSpectrumAnalyzerAnalyzeAt({
    required SpectrumAnalyzer that,
    required AudioBuffer buffer,
    required int positionMs,
  });

  double crateApiSpectrumSpectrumAnalyzerGetAmplitude({
    required SpectrumAnalyzer that,
  });

  Float32List crateApiSpectrumSpectrumAnalyzerGetBands({
    required SpectrumAnalyzer that,
  });

  Uint8List crateApiSpectrumSpectrumAnalyzerGetFrequencyData({
    required SpectrumAnalyzer that,
  });

  Future<SpectrumAnalyzer> crateApiSpectrumSpectrumAnalyzerNew({
    required int sampleRate,
    required int fftSize,
    required double smoothing,
  });

  void crateApiSpectrumSpectrumAnalyzerPushInterleaved({
    required SpectrumAnalyzer that,
    required List<double> samples,
    required int channels,
  });

  void crateApiSpectrumSpectrumAnalyzerPushSamples({
    required SpectrumAnalyzer that,
    required List<double> samples,
  });

  void crateApiSpectrumSpectrumAnalyzerReset({required SpectrumAnalyzer that});

  Future<void> crateApiSpectrumInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioBuffer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioBuffer;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AudioBufferPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SpectrumAnalyzer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SpectrumAnalyzer;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SpectrumAnalyzerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AudioBuffer> crateApiSpectrumAudioBufferDecode({
    required List<int> fileBytes,
    required String fileExtension,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(fileBytes, serializer);
          sse_encode_String(fileExtension, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumAudioBufferDecodeConstMeta,
        argValues: [fileBytes, fileExtension],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumAudioBufferDecodeConstMeta =>
      const TaskConstMeta(
        debugName: "AudioBuffer_decode",
        argNames: ["fileBytes", "fileExtension"],
      );

  @override
  double crateApiSpectrumAudioBufferDurationMs({required AudioBuffer that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumAudioBufferDurationMsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumAudioBufferDurationMsConstMeta =>
      const TaskConstMeta(
        debugName: "AudioBuffer_duration_ms",
        argNames: ["that"],
      );

  @override
  bool crateApiSpectrumAudioBufferHasData({required AudioBuffer that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumAudioBufferHasDataConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumAudioBufferHasDataConstMeta =>
      const TaskConstMeta(
        debugName: "AudioBuffer_has_data",
        argNames: ["that"],
      );

  @override
  int crateApiSpectrumAudioBufferSampleRate({required AudioBuffer that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumAudioBufferSampleRateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumAudioBufferSampleRateConstMeta =>
      const TaskConstMeta(
        debugName: "AudioBuffer_sample_rate",
        argNames: ["that"],
      );

  @override
  Float32List crateApiSpectrumSpectrumAnalyzerAnalyzeAt({
    required SpectrumAnalyzer that,
    required AudioBuffer buffer,
    required int positionMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
            that,
            serializer,
          );
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
            buffer,
            serializer,
          );
          sse_encode_u_32(positionMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumSpectrumAnalyzerAnalyzeAtConstMeta,
        argValues: [that, buffer, positionMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumSpectrumAnalyzerAnalyzeAtConstMeta =>
      const TaskConstMeta(
        debugName: "SpectrumAnalyzer_analyze_at",
        argNames: ["that", "buffer", "positionMs"],
      );

  @override
  double crateApiSpectrumSpectrumAnalyzerGetAmplitude({
    required SpectrumAnalyzer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumSpectrumAnalyzerGetAmplitudeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumSpectrumAnalyzerGetAmplitudeConstMeta =>
      const TaskConstMeta(
        debugName: "SpectrumAnalyzer_get_amplitude",
        argNames: ["that"],
      );

  @override
  Float32List crateApiSpectrumSpectrumAnalyzerGetBands({
    required SpectrumAnalyzer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumSpectrumAnalyzerGetBandsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumSpectrumAnalyzerGetBandsConstMeta =>
      const TaskConstMeta(
        debugName: "SpectrumAnalyzer_get_bands",
        argNames: ["that"],
      );

  @override
  Uint8List crateApiSpectrumSpectrumAnalyzerGetFrequencyData({
    required SpectrumAnalyzer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumSpectrumAnalyzerGetFrequencyDataConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSpectrumSpectrumAnalyzerGetFrequencyDataConstMeta =>
      const TaskConstMeta(
        debugName: "SpectrumAnalyzer_get_frequency_data",
        argNames: ["that"],
      );

  @override
  Future<SpectrumAnalyzer> crateApiSpectrumSpectrumAnalyzerNew({
    required int sampleRate,
    required int fftSize,
    required double smoothing,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(sampleRate, serializer);
          sse_encode_u_32(fftSize, serializer);
          sse_encode_f_32(smoothing, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumSpectrumAnalyzerNewConstMeta,
        argValues: [sampleRate, fftSize, smoothing],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumSpectrumAnalyzerNewConstMeta =>
      const TaskConstMeta(
        debugName: "SpectrumAnalyzer_new",
        argNames: ["sampleRate", "fftSize", "smoothing"],
      );

  @override
  void crateApiSpectrumSpectrumAnalyzerPushInterleaved({
    required SpectrumAnalyzer that,
    required List<double> samples,
    required int channels,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
            that,
            serializer,
          );
          sse_encode_list_prim_f_32_loose(samples, serializer);
          sse_encode_u_32(channels, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumSpectrumAnalyzerPushInterleavedConstMeta,
        argValues: [that, samples, channels],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumSpectrumAnalyzerPushInterleavedConstMeta =>
      const TaskConstMeta(
        debugName: "SpectrumAnalyzer_push_interleaved",
        argNames: ["that", "samples", "channels"],
      );

  @override
  void crateApiSpectrumSpectrumAnalyzerPushSamples({
    required SpectrumAnalyzer that,
    required List<double> samples,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
            that,
            serializer,
          );
          sse_encode_list_prim_f_32_loose(samples, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumSpectrumAnalyzerPushSamplesConstMeta,
        argValues: [that, samples],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumSpectrumAnalyzerPushSamplesConstMeta =>
      const TaskConstMeta(
        debugName: "SpectrumAnalyzer_push_samples",
        argNames: ["that", "samples"],
      );

  @override
  void crateApiSpectrumSpectrumAnalyzerReset({required SpectrumAnalyzer that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumSpectrumAnalyzerResetConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumSpectrumAnalyzerResetConstMeta =>
      const TaskConstMeta(
        debugName: "SpectrumAnalyzer_reset",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiSpectrumInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSpectrumInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSpectrumInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioBuffer => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioBuffer => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SpectrumAnalyzer => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SpectrumAnalyzer => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer;

  @protected
  AudioBuffer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioBufferImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SpectrumAnalyzer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpectrumAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SpectrumAnalyzer
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpectrumAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AudioBuffer
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioBufferImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SpectrumAnalyzer
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpectrumAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AudioBuffer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioBufferImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SpectrumAnalyzer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpectrumAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AudioBuffer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioBufferImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SpectrumAnalyzer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SpectrumAnalyzerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SpectrumAnalyzer
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SpectrumAnalyzerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AudioBuffer
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioBufferImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SpectrumAnalyzer
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SpectrumAnalyzerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AudioBuffer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioBufferImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SpectrumAnalyzer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SpectrumAnalyzerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
    AudioBuffer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioBufferImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    SpectrumAnalyzer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SpectrumAnalyzerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    SpectrumAnalyzer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SpectrumAnalyzerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
    AudioBuffer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioBufferImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    SpectrumAnalyzer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SpectrumAnalyzerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioBuffer(
    AudioBuffer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioBufferImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpectrumAnalyzer(
    SpectrumAnalyzer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SpectrumAnalyzerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class AudioBufferImpl extends RustOpaque implements AudioBuffer {
  // Not to be used by end users
  AudioBufferImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AudioBufferImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AudioBuffer,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioBuffer,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioBufferPtr,
  );

  /// Get the duration in milliseconds.
  double durationMs() =>
      RustLib.instance.api.crateApiSpectrumAudioBufferDurationMs(that: this);

  /// Whether the buffer has audio data.
  bool hasData() =>
      RustLib.instance.api.crateApiSpectrumAudioBufferHasData(that: this);

  /// Get the sample rate.
  int sampleRate() =>
      RustLib.instance.api.crateApiSpectrumAudioBufferSampleRate(that: this);
}

@sealed
class SpectrumAnalyzerImpl extends RustOpaque implements SpectrumAnalyzer {
  // Not to be used by end users
  SpectrumAnalyzerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SpectrumAnalyzerImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SpectrumAnalyzer,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SpectrumAnalyzer,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_SpectrumAnalyzerPtr,
  );

  /// Analyze at a specific position in an AudioBuffer. ONE FFT — instant.
  /// Call this every frame during playback.
  Float32List analyzeAt({
    required AudioBuffer buffer,
    required int positionMs,
  }) => RustLib.instance.api.crateApiSpectrumSpectrumAnalyzerAnalyzeAt(
    that: this,
    buffer: buffer,
    positionMs: positionMs,
  );

  /// Get overall amplitude (0.0–1.0).
  double getAmplitude() => RustLib.instance.api
      .crateApiSpectrumSpectrumAnalyzerGetAmplitude(that: this);

  /// Get 4 frequency bands (0.0–1.0).
  Float32List getBands() =>
      RustLib.instance.api.crateApiSpectrumSpectrumAnalyzerGetBands(that: this);

  /// Get frequency data as 0–255 bytes (like getByteFrequencyData).
  Uint8List getFrequencyData() => RustLib.instance.api
      .crateApiSpectrumSpectrumAnalyzerGetFrequencyData(that: this);

  /// Push interleaved multi-channel samples.
  void pushInterleaved({
    required List<double> samples,
    required int channels,
  }) => RustLib.instance.api.crateApiSpectrumSpectrumAnalyzerPushInterleaved(
    that: this,
    samples: samples,
    channels: channels,
  );

  /// Push raw PCM f32 mono samples for live streaming (mic/AI).
  void pushSamples({required List<double> samples}) =>
      RustLib.instance.api.crateApiSpectrumSpectrumAnalyzerPushSamples(
        that: this,
        samples: samples,
      );

  /// Reset state.
  void reset() =>
      RustLib.instance.api.crateApiSpectrumSpectrumAnalyzerReset(that: this);
}
