// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_bands`, `run_fft`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioBuffer>>
abstract class AudioBuffer implements RustOpaqueInterface {
  /// Decode audio file bytes to PCM. Fast — no FFT.
  /// Supports MP3, WAV, OGG, FLAC, AAC.
  static Future<AudioBuffer> decode({
    required List<int> fileBytes,
    required String fileExtension,
  }) => RustLib.instance.api.crateApiSpectrumAudioBufferDecode(
    fileBytes: fileBytes,
    fileExtension: fileExtension,
  );

  /// Get the duration in milliseconds.
  double durationMs();

  /// Whether the buffer has audio data.
  bool hasData();

  /// Get the sample rate.
  int sampleRate();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SpectrumAnalyzer>>
abstract class SpectrumAnalyzer implements RustOpaqueInterface {
  /// Analyze at a specific position in an AudioBuffer. ONE FFT — instant.
  /// Call this every frame during playback.
  Float32List analyzeAt({required AudioBuffer buffer, required int positionMs});

  /// Get overall amplitude (0.0–1.0).
  double getAmplitude();

  /// Get 4 frequency bands (0.0–1.0).
  Float32List getBands();

  /// Get frequency data as 0–255 bytes (like getByteFrequencyData).
  Uint8List getFrequencyData();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new analyzer.
  /// - `sample_rate`: 44100 for music, 16000/24000 for AI voice
  /// - `fft_size`: 2048 recommended
  /// - `smoothing`: 0.85 matches WaveForge
  static Future<SpectrumAnalyzer> newInstance({
    required int sampleRate,
    required int fftSize,
    required double smoothing,
  }) => RustLib.instance.api.crateApiSpectrumSpectrumAnalyzerNew(
    sampleRate: sampleRate,
    fftSize: fftSize,
    smoothing: smoothing,
  );

  /// Push interleaved multi-channel samples.
  void pushInterleaved({required List<double> samples, required int channels});

  /// Push raw PCM f32 mono samples for live streaming (mic/AI).
  void pushSamples({required List<double> samples});

  /// Reset state.
  void reset();
}
